# Generated by Django 6.0.2 on 2026-03-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_payment_confirmed_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('served', 'Served')], default='pending_payment', max_length=20),
        ),
    ]
