# Generated by Django 6.0.2 on 2026-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_table_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
