# Generated by Django 6.0.2 on 2026-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menuitem_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_chef_special',
            field=models.BooleanField(default=False),
        ),
    ]
